### ISSUE TITLE
Setting environmental variables for database connection config not working

### ISSUE THREAD

**Issue by aarobc** [bitnami/bitnami-docker-opencart#1]
docker-compose.yml:
```
version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: opencart

  opencart:
    image: bitnami/opencart:latest
    environment:
      MARIADB_PASSWORD: secret
      MARIADB_HOST: db
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
```
Output when run:
```
❯ docker-compose run --rm opencart
Creating testcart_db_1
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing opencart
opencar INFO  Creating the database...
mysqlCo INFO  Trying to connect to MySQL server
mysqlCo INFO  Found MySQL server listening at db:3306
Error executing 'postInstallation': Cannot connect to MySQL server:
ERROR 1045 (28000): Access denied for user 'root'@'172.25.0.3' (using password: NO)
```

It looks like it's not reading the `MARIADB_PASSWORD` parameter.
