### ISSUE TITLE
When customizing the image (following doc) the opencart_storage folder gets empty

### ISSUE THREAD

**Issue by redochka** [bitnami/bitnami-docker-opencart#100]
**Description**

When customizing the image by following the doc and using docker compose the opencart_storage folder gets empty which makes opencart unable to run.

**Steps to reproduce the issue:**

1. Follow doc from https://github.com/bitnami/bitnami-docker-opencart#customize-this-image
2. So create a dockerfile
3. Create a docker-compose file
4. Run : docker-compose up

**Describe the results you received:**

The `/bitnami/opencart_storage` is empty

**Describe the results you expected:**

The `/bitnami/opencart_storage` must not be empty

**Comment by pablogalegoc** [comment]
Hi @redochka!

I couldn’t reproduce your issue. Everything worked creating the following Dockerfile similar to the documentation example:
```Dockerfile
FROM bitnami/opencart
LABEL maintainer “Bitnami <containers@bitnami.com>”
## Change user to perform privileged actions
USER 0
## Install ‘vim’
RUN install_packages vim
## Revert to the original non-root user
USER 1001
```
And using this docker-compose.yaml: https://github.com/bitnami/bitnami-docker-opencart/blob/master/docker-compose.yml
Only changing:
```diff
   opencart:
-    image: bitnami/opencart:latest
+    build: .
```
Could you share an example of `Dockerfile` and `docker-compose.yml` that cause the issue?

**Comment by redochka** [comment]
Your example is indeed working but not mine. Here is my Dockerfile:

```
FROM bitnami/opencart:3

## Change user to perform privileged actions
USER 0

## Install 'vim'
RUN install_packages vim

## Revert to the original non-root user
USER 1001

## Copy vqmod
COPY ./assets/vqmod-2.6.4-opencart/ /opt/bitnami/opencart/
#COPY ./assets/vqmod-2.6.4-opencart/ /
```

and here is my `docker-compose.yml`

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    #    image: 'docker.io/bitnami/opencart:3-debian-10'
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=162.55.208.197
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      # - 'opencart_data:/bitnami/opencart'
      - /home/reda/docker/volumes/opencart-persistence:/bitnami/opencart
      - 'opencart_storage_data2:/bitnami/opencart_storage/'

    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
#  opencart_data:
#    driver: local
  opencart_storage_data2:
    driver: local
```
