### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by svkamp** [bitnami/bitnami-docker-opencart#30]
Getting a warning on the certs you use for https, can we generate and install  our own ?

**Comment by prydonius** [comment]
Hey @svkamp, the steps to follow to use a custom SSL cert are here: https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates. However, in my testing this did not work because the Apache initialisation creates and overwrites the certs in the volume. I'll file an issue separately to get that fixed.

In the meantime, to use your own cert, edit your docker-compose file to use a host mounted directory for Apache configuration:
```
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - './apache-conf:/bitnami/apache'
      - 'php_data:/bitnami/php'
```

Bring up OpenCart (you might need to tear down anything you had previously with `docker-compose down -v`) and once the application is started you should find that `./apache-conf/conf/bitnami/certs` has the default self-signed cert. You can choose to install this cert to remove the warning or replace these files with your own certs and then restart OpenCart using `docker-compose restart opencart`.

**Comment by nirfse** [comment]
@prydonius 

> I'll file an issue separately to get that fixed.

Hey, is there any progress with that issue?

**Comment by tompizmor** [comment]
Hi @nirfse,
I think the issue is this one https://github.com/bitnami/bitnami-docker-apache/issues/63 but it seems to be open yet.
I guess you just hit the same issue with one of the latest images right?

**Comment by nirfse** [comment]
@tompizmor Right, it's the very same issue. While there's a workaround, it'd be much more convenient to be able to point to (self-signed/root-accepted) cert files in `docker-compose.yml` config on the first run. Or at least document this behavior, add workarounds to the documentation.

**Comment by tompizmor** [comment]
Thank for confirming it @nirfse! I will re-bump this task internally to get it fixed.

**Comment by tompizmor** [comment]
Hi @nirfse!

We have just updated the Opencart docker image so it allows mounting the certificates during the first initialization.

In order to test it create a `certs` local directory and put there your `server.crt` and `server.key`. Then use this docker-compose:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=172.17.0.5
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
      - './certs:/opt/bitnami/apache/certs'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
```

For more information please check the [Apache Readme](https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates)
