### ISSUE TITLE
New Theme Update Issue

### ISSUE THREAD

**Issue by iedmrc** [bitnami/bitnami-docker-opencart#51]
Hi,
I use bitnami-docker-opencart image smoothly but with a problem. This is a part from my docker-compose.yml:

```
opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - OPENCART_USERNAME=blabla
      - OPENCART_PASSWORD=blabla
      - OPENCART_EMAIL=blabla
      - OPENCART_HOST=blabla
      - MARIADB_PASSWORD=blabla
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../web_app:/bitnami'
    depends_on:
      - mariadb
```

I uploaded my new theme to web_app local directory and i can see it is mounted to opencart container very well. When I enter into container with exec command, i can see files under `/bitnami/opencart` directory. But bitnami runs apache from /opt/bitnami/opencart and it doesn't sync with `/bitnami/opencart` directory. So i cannot use my new theme with bitnami-opencart- image.

Why this image works with this way? What should be the best practice to solve this problem?

Thank you for your helps.
