### ISSUE TITLE
Important security notification! Move storage directory

### ISSUE THREAD

**Issue by ckpiggy** [bitnami/bitnami-docker-opencart#52]
**Description**
I use opencart image with docker-compose like this:
```
version: '3.2'
services:
  mariadb:
    container_name: mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: bind
        source: ./mariadb
        target: /bitnami
  opencart:
    container_name: opencart
    image: 'bitnami/opencart:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./opencart_data
        target: /bitnami
    depends_on:
      - mariadb
```
And when I go to admin I got
![2018-01-11 9 55 46](https://user-images.githubusercontent.com/6531171/34829313-3e61ea92-f71b-11e7-84a3-f0caec7283c5.png)

It ask me to move `storage` directory. And after I click auto move, I got:

![2018-01-11 10 19 58](https://user-images.githubusercontent.com/6531171/34830060-acc5ba02-f71d-11e7-9740-bb649d81fd29.png)

permission deny....

How should I solve this?
