### ISSUE TITLE
Failed to install extension

### ISSUE THREAD

**Issue by betonetotbo** [bitnami/bitnami-docker-opencart#53]
Version: `3.0.0-2-r1`

I tried to install an extesion for [REST API](https://github.com/opencartbrasil/opencart-rest-api).

When I install it via `Extension >> Installer` menu I got: `The directory api.php is not allowed to be written to!`

![image](https://user-images.githubusercontent.com/5444923/38436268-82237850-39aa-11e8-8d6f-f1be1ca67933.png)

I think this is an permission problem of the image. Am I correct? 
How can I solve it?

This is my `docker-compose.yaml`:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:3.0.0-2-r1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=opencart
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
    hostname: opencart
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
```

**Comment by juan131** [comment]
hi @betonetotbo 

Another user recently reported a similar issue with permissions. See https://github.com/bitnami/bitnami-docker-opencart/issues/52 

I will add this information to the internal task we have to fix this issue. Thanks so much for reporting it. We will keep you updated.

**Comment by danielbjornadal** [comment]
Any update on this issue?

**Comment by juan131** [comment]
Hi @danielbjornadal 

As mentioned on the issue #52 we released a new version of the image facing the associated problem. Could you try to use the latest Bitnami Opencart image and let us know if you still face it?

**Comment by juan131** [comment]
Hi @olgaPetrishin 

I could install without any issue both the extensions below (see screenshots):

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18427
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=28828

![screenshot 2018-11-28 at 08 28 37](https://user-images.githubusercontent.com/6740773/49135866-49d79600-f2e8-11e8-9d49-c8013b5850b7.png)
![screenshot 2018-11-28 at 08 30 49](https://user-images.githubusercontent.com/6740773/49135871-4b08c300-f2e8-11e8-82aa-c927c21da081.png)


Could you share the link to the extension you're using so I can download it and install it?

**Comment by malkevych** [comment]
I will record a video review of this problem today in the evening.

**Comment by olgaPetrishin** [comment]
Hi @juan131
You can try for this extention for example https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=cSr19GE8678CLZL6jEJI56s0SWqw7N2M&extension_id=33206&filter_license=0

Before installing module i give (chmod a+rwx -R bitnami/) permissions for the whole folder bitnami inside docker but it does not help.
I got current errors in error log for it:
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/module/amazon_login.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/module/amazon_login.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/module/amazon_pay.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/module/amazon_pay.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_address.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/payment/amazon_login_pay_address.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_confirm.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/payment/amazon_login_pay_confirm.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_failure.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/payment/amazon_login_pay_failure.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218
2018-11-28 8:32:00 - PHP Warning:  rename(/bitnami/opencart/system/storage/upload/tmp-iV9nV9CSDi/upload/catalog/view/theme/default/template/extension/payment/amazon_login_pay_payment.twig,/opt/bitnami/opencart/catalog/view/theme/default/template/extension/payment/amazon_login_pay_payment.twig): Operation not permitted in /opt/bitnami/opencart/admin/controller/marketplace/install.php on line 218

**Comment by juan131** [comment]
Hi @olgaPetrishin 

I could also install that extension without issues, see the screenshot below:

![screenshot 2018-11-28 at 10 37 23](https://user-images.githubusercontent.com/6740773/49143004-5c5acb00-f2fa-11e8-972d-22272a1ca505.png)

What version of the extension did you download? Please note I used version 3.0.2.

> Before installing module i give (chmod a+rwx -R bitnami/) permissions for the whole folder bitnami inside docker but it does not help.

You shouldn't need to do that. Are you deploying Opencart from scratch? I mean, do you have a data from previous deployments? 

I'm using the [this docker-compose.yaml](https://github.com/bitnami/bitnami-docker-opencart/blob/master/docker-compose.yml) and running the commands below:

```
$ docker-compose down -v --rmi all
$ docker-compose up -d 
```

**Comment by olgaPetrishin** [comment]
Hi @juan131 
Yes i am 
- running docker-compose down -v --rmi all
- i am using module version  3.0.2.
- i am deploying Opencart from scratch according to this documentation https://hub.docker.com/r/bitnami/opencart/

The only thing is that i am working on windows 10, could it somehow effect this? But i tried your image for prestashop and everything worked perfectly. (https://github.com/bitnami/bitnami-docker-prestashop)

**Comment by juan131** [comment]
> The only thing is that i am working on windows 10, could it somehow effect this?

It could be related. Does the error appears when using a `docker-compose.yaml` without volumes? For instance, the one below:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
  opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
```

**Comment by malkevych** [comment]
Tried again, for me now everything is ok!!
Many Thanks!!!

My docker-compose.yml

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
```
