### ISSUE TITLE
Timeout when "Upgrading OpenCart..."

### ISSUE THREAD

**Issue by elliottkopp** [bitnami/bitnami-docker-opencart#56]
**Description**

When following the [upgrade instructions in the readme](https://github.com/bitnami/bitnami-docker-opencart#upgrade-this-application), I get an error `opencart_1  | Error executing 'postInstallation': Timeout: did not get to load all resources on this page` when starting the new opencart container.

This only happens when I have named volumes mounted to the opencart container.

**Steps to reproduce the issue:**
1. Use the docker-compose file I have pasted in the bottom of this bug report
2. `docker-compose up -d` and let everything come up
3. `docker-compose down`
    * Note that this will stop and remove the containers, but not the named volumes created from the docker-compose file
4. `docker-compose up -d`

**Describe the results you received:**

The opencart container (not the maria container), throws an error and fails to start.  The error received is `Error executing 'postInstallation': Timeout: did not get to load all resources on this page`.

**Describe the results you expected:**

I would expect the opencart container to start.

**Additional information you deem important (e.g. issue happens only occasionally):**

Only happens when the opencart container has a volume mapped.  I use docker-compose to create named volumes.  This test is repeatable with named volumes created manually via the docker CLI as well and linked in the docker-compose as external volumes.

Note that in the steps to reproduce, I did not list a `docker pull` command.  That's because it's not necessary to reproduce this bug.  The bug is reproducible even without pulling a new version between stopping the old containers and starting the new ones.  I'm using the latest version of both containers (maria and opencart).

The docker-compose I have pasted below is almost an exact copy/paste of the example with volumes in the readme for this project, except I used named volumes instead of hard-coded paths on the host.

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.772GiB
Name: chicago
ID: 66X7:JV3D:MP7U:JNER:6OXY:B4BP:O2KY:7GAF:VPNA:R4TG:EJKD:UW77
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

Here is the docker-compose.yml file I'm using
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb:/bitnami'
  opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb:
  opencart:
```
