### ISSUE TITLE
OPENCART_HOST does nothing

### ISSUE THREAD

**Issue by ryanelian** [bitnami/bitnami-docker-opencart#61]
**Description**

I am using the docker image, and `OPENCART_HOST` environment variable does nothing... (I am still getting redirected to 127.0.0.1)

This is my `docker-compose.yml`: (password redacted)

```
version: '3'

networks:
  web:
    external: true
  internal:
    driver: overlay

volumes:
  shop_data:
    external: true
  shop_mariadb:
    external: true

services:
  mariadb:
    image: mariadb
    networks:
      - internal
    environment:
      - MYSQL_DATABASE=bitnami_opencart
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - shop_mariadb:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
  opencart:
    image: bitnami/opencart
    networks:
      - web
      - internal
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_HOST=shop.something.com
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_DATABASE_USER=root
      - OPENCART_DATABASE_PASSWORD=
    volumes:
      - shop_data:/bitnami
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.backend: "shop"
        traefik.frontend.rule: "Host:shop.something.com"
        traefik.port: "80"
```

**Steps to reproduce the issue:**

1. Use `docker stack deploy -c docker-compose.yml shop`
2. Visit `shop.something.com`

**Describe the results you received:**

The page is messed up because everything redirects to `127.0.0.1`

![image](https://user-images.githubusercontent.com/8892187/49757943-37019000-fcf0-11e8-8df8-afc88972f912.png)

**Describe the results you expected:**

The host resolves correctly to the value given in the environment variable

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`: 

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iv8djqo3rrlvklzi1xfxkw3pi
 Is Manager: true
 ClusterID: irsvtox2dt4z1dhj5kph5owcs
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.10.1.171
 Manager Addresses:
  10.10.1.171:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.13.2 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.81-coreos
Operating System: Container Linux by CoreOS 1911.4.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.792GiB
Name: accelist-production
ID: EBEJ:62AX:6ETC:IEOV:MZ2Z:MZP5:NQL2:QIUO:AR6F:VGIQ:5QYL:YQEN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
I was unable to reproduce using the **docker-compose.yaml** below:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=shop.something.com
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
```

After adding `shop.something.com` to my `/etc/hosts`:

```
127.0.0.1       localhost shop.something.com
...
```

I access to http://shop.something.com/

![screenshot 2018-12-12 at 11 15 06](https://user-images.githubusercontent.com/6740773/49862822-46bbca00-fdff-11e8-9fe4-6176f0261fc3.png)

You can also check it in the logs:

```
$ docker-compose logs opencart
...
opencart_1  | opencar INFO  ########################################################################
opencart_1  | opencar INFO   Installation parameters for opencart:
opencart_1  | opencar INFO     Username: user
opencart_1  | opencar INFO     Password: **********
opencart_1  | opencar INFO     Email: user@example.com
opencart_1  | opencar INFO     Site URL: http://shop.something.com/
opencart_1  | opencar INFO   (Passwords are not shown for security reasons)
opencart_1  | opencar INFO  ########################################################################
opencart_1  | opencar INFO
opencart_1  | nami    INFO  opencart successfully initialized
opencart_1  | INFO  ==> Starting opencart...
```
