### ISSUE TITLE
Trying to rebuild the images

### ISSUE THREAD

**Issue by ifridemberg** [bitnami/bitnami-docker-opencart#62]
HI, 
I would like to set up a container with MySQL instead of MariaDB but I have has some troubles. 
When I try to rebuild the images to change the env variables it gets me a follow message.
"COPY failed: stat /var/lib/docker/tmp/docker-builder047842743/rootfs: no such file or directory"
I think the problem is the FROM bitnami/minideb-extras:stretch-r248 line, but I not sure. I attempted with -r220 but I got the same outcome.
I attach the modified Dockerfile, that I'm using. I'll thank any review that can help me. 

best regard

Ignacio Fridemberg

[Dockerfile.txt](https://github.com/bitnami/bitnami-docker-opencart/files/2751410/Dockerfile.txt)

**Comment by andresbono** [comment]
Hi @ifridemberg, if you want to change the MariaDB container to use MySQL you can try with the `docker-compose.yml` below. There is no need to rebuild the opencart container.

```
version: '2'
services:
  mysql:
    image: 'bitnami/mysql:5.7'
    environment:
      - MYSQL_USER=bn_opencart
      - MYSQL_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mysql_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:3'
    environment:
      - NAMI_LOG_LEVEL=trace
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local
```
