### ISSUE TITLE
Failed to initialize without clear error message

### ISSUE THREAD

**Issue by ryanelian** [bitnami/bitnami-docker-opencart#72]
**Description**

My opencart on kubernetes (non-helm) failed to initialize:

```
 Welcome to the Bitnami opencart container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing opencart
opencar INFO  Preparing webserver environment...
opencar INFO  Preparing PHP environment...
opencar INFO  Upgrading OpenCart...
Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/install/index.php?route=upgrade/upgrade
Server returned status code 500 from http://127.0.0.1/install/index.php?route=upgrade/upgrade 
```

This is my kubernetes YAML file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx-shop-deployment
  labels:
    app: xxx-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-shop
  template:
    metadata:
      labels:
        app: xxx-shop
    spec:
      volumes:
      - name: xxx-shop-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: xxx-shop-app
        image: bitnami/opencart:3.0.3-2
        volumeMounts:
        - name: xxx-shop-volume
          subPath: xxx-shop
          mountPath: /bitnami
        env:
        - name: MARIADB_HOST
          value: db.xxx.com
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: OPENCART_HOST
          value: shop.xxx.com
        - name: OPENCART_DATABASE_NAME
          value: bitnami_opencart
        - name: OPENCART_DATABASE_USER
          value: root
        - name: OPENCART_DATABASE_PASSWORD
          value: xxxx
```

**Steps to reproduce the issue:**

1. Setup a database on server referenced by above YAML: `docker run -d -p 3306:3306 -e MYSQL_DATABASE=bitnami_opencart -e MYSQL_ROOT_PASSWORD=xxx -v shop:/var/lib/mysql --restart always mariadb`
2. `kubectl apply -f setup.yaml` above
3. OpenCart crash loop.

**Describe the results you received:**

```
Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/install/index.php?route=upgrade/upgrade
```

That error is obscure, I tried googling around without result.

**Describe the results you expected:**

OpenCart successfully initialized.

**Additional information you deem important (e.g. issue happens only occasionally):**

We haven't tried the helm chart, but we are not supposed to use helm.

**Version**

- Output of `docker version`:

```
Docker version 18.09.6, build 481bc77
```

- Output of `docker info`:

```
Containers: 28
 Running: 22
 Paused: 0
 Stopped: 6
Images: 30
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.863GiB
Name: 
ID: SRQL:NTYJ:L2TW:4GU4:NMBQ:MNY6:P32N:E3PH:K5YR:TVZW:OOBX:KTG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

kubectl version:

```
root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
