### ISSUE TITLE
Persistent images & extensions

### ISSUE THREAD

**Issue by drticcz** [bitnami/bitnami-docker-opencart#92]
Currently it is pain to use this image in production mode as the 'image' folder is not persistent. It would be also great to have a possibility to persist folders that  contains extensions.

**Comment by drticcz** [comment]
I found that in #51 there was new variable added to select persistent data, however it is breaking my container.
When I add `OPENCART_DATA_TO_PERSIST=image`, the container won't start as it fails to load the original config.php that should be persistent by default...

`opencart_1  | PHP Warning:  require(/opt/bitnami/opencart/config.php): failed to open stream: No such file or directory in Command line code on line 1`

**Comment by dtrouillet** [comment]
Hi, I try the same but with `OPENCART_DATA_TO_PERSIST=image config.php admin/config.php` but it doesn't work. Opencart start, but the directory image is not recognized. I think OPENCART_DATA_TO_PERSIST must have file and not folder (like image 😢 ).

**Comment by drticcz** [comment]
I think the best way to define multiple items would be array, so like this. That worked for me but it suddenly conflicts with other stuff I have mounted in /opt/bitnami/opencart like `.well-known` folder for the certbot SSL certificate renewal.

`OPENCART_DATA_TO_PERSIST=["image", "config.php", "admin/config.php"]`

**Comment by alemorcuq** [comment]
Hi, @drticcz, @dtrouillet.

I have deployed Opencart setting `OPENCART_DATA_TO_PERSIST=image config.php admin/config.php` and the `image` folder is getting persisted:

```
I have no name!@c736177bdfd2:/opt/bitnami/opencart$ ls -la /opt/bitnami/opencart/image
lrwxrwxrwx 1 1001 root 23 Dec 16 08:09 /opt/bitnami/opencart/image -> /bitnami/opencart/image

I have no name!@c736177bdfd2:/opt/bitnami/opencart$ ls -la /bitnami/opencart/image/
total 148
drwxrwxr-x 5   1001 root  4096 Dec 16 08:09 .
drwxrwxr-x 4 daemon root  4096 Dec 16 08:09 ..
drwxrwxr-x 2   1001 root  4096 Dec 16 08:09 cache
drwxrwxr-x 3   1001 root  4096 Dec 16 08:09 catalog
-rw-rw-r-- 1   1001 root 65814 Dec 16 08:09 no_image.png
drwxrwxr-x 3   1001 root  4096 Dec 16 08:09 payment
-rw-rw-r-- 1   1001 root 56256 Dec 16 08:09 placeholder.png
-rw-rw-r-- 1   1001 root  2178 Dec 16 08:09 profile.png
```

What issues are you finding?

**Comment by drticcz** [comment]
Yes, this itself works for me. What does not work for me is the combination
of this and another folder mounted to the /opt/bitnami/opencart as it is
trying to clean up this folder and failing to do so...

This is how I mount it in my docker-compose. I need it so my SSL certs are
automatically renewed by the certbots... Should I choose a different
approach?
volumes:
- '/home/docker/certs/.well-known:/opt/bitnami/opencart/.well-known'
--
Jan Polák

**Comment by alemorcuq** [comment]
Using this `docker-compose.yml` file I'm not able to reproduce your issue:

```
❯ cat docker-compose.yml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_DATA_TO_PERSIST=image config.php admin/config.php
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
      - '.well-known:/opt/bitnami/opencart/.well-known'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
```

Could you share yours?
