### ISSUE TITLE
Accessing google cloud sql from bitnami-docker-opencart

### ISSUE THREAD

**Issue by amuntasim** [bitnami/bitnami-docker-opencart#93]
**Description**

**Can't access cloud sql from  bitnami docker-opencart**

Here is my docker-compose.yml file

```
version: '2'
services:
  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: /cloud_sql_proxy --dir=/cloudsql -instances=ivipni-279915:asia-southeast1:opencart=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/credentials.json
    volumes:
    - ./config/cloudsql-credentials.json:/secrets/cloudsql/credentials.json
    ports:
    - 127.0.0.1:3306:3306

  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '8001:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=cloudsql-proxy
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=****       
      - OPENCART_DATABASE_NAME=****     
      - OPENCART_DATABASE_PASSWORD=****
      - ALLOW_EMPTY_PASSWORD=no 
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - cloudsql-proxy
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local

```

**Steps to reproduce the issue:**

1. `docker-compose up`

**Describe the results you received:**

```
pencart_1        | opencart 06:10:03.24 
opencart_1        | opencart 06:10:03.26 Welcome to the Bitnami opencart container
opencart_1        | opencart 06:10:03.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
opencart_1        | opencart 06:10:03.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
opencart_1        | opencart 06:10:03.27 
opencart_1        | opencart 06:10:03.30 INFO  ==> ** Starting OpenCart setup **
opencart_1        | opencart 06:10:03.40 INFO  ==> Configuring PHP options
opencart_1        | opencart 06:10:03.40 INFO  ==> Setting PHP expose_php option
opencart_1        | opencart 06:10:03.54 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
opencart_1        | opencart 06:10:03.64 INFO  ==> Ensuring OpenCart directories exist
opencart_1        | opencart 06:10:03.65 INFO  ==> Trying to connect to the database server
cloudsql-proxy_1  | 2020/12/14 06:10:04 New connection for "ivipni-279915:asia-southeast1:opencart"
cloudsql-proxy_1  | 2020/12/14 06:10:04 Client closed local connection on 172.24.0.2:3306
opencart_1        | opencart 06:10:04.40 INFO  ==> Running install script
cloudsql-proxy_1  | 2020/12/14 06:10:06 New connection for "ivipni-279915:asia-southeast1:opencart"
cloudsql-proxy_1  | 2020/12/14 06:10:15 Client closed local connection on 172.24.0.2:3306
kiranaprod_opencart_1 exited with code 255
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 44
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1028-gcp
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.94GiB
 Name: ivipni-prod-vm1
 ID: HRUX:5VLJ:QT5W:P53R:SMK5:SUGL:QPXH:CVJO:EMOC:GC2Z:GLOZ:ZK7T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

I'm able to connect the cloud sql from other docker instance but not from the bitnami docker

**Comment by juan131** [comment]
Hi @amuntasim 

Could you please add the environment variable: `BITNAMI_DEBUG=true`? That will increase the verbosity in the logs so we might more information about what's going on and why Opencart is unable to connect to the database.

**Comment by amuntasim** [comment]
Hi @juan131 

Here is the detail error after adding BITNAMI_DEBUG=true

```
Fatal error: Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40' in /opt/bitnami/opencart/system/library/db/mysqli.php:40
opencart_1        | Stack trace:
opencart_1        | #0 /opt/bitnami/opencart/system/library/db.php(45): DB\MySQLi->query('SET @@session.s...')
opencart_1        | #1 /opt/bitnami/opencart/install/cli_install.php(213): DB->query('SET @@session.s...')
opencart_1        | #2 /opt/bitnami/opencart/install/cli_install.php(133): setup_db(Array)
opencart_1        | #3 /opt/bitnami/opencart/install/cli_install.php(352): install(Array)
opencart_1        | #4 {main}
opencart_1        |   thrown in /opt/bitnami/opencart/system/library/db/mysqli.php on line 40
opencart_1        | PHP Fatal error:  Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40' in /opt/bitnami/opencart/system/library/db/mysqli.php:40
opencart_1        | Stack trace:
opencart_1        | #0 /opt/bitnami/opencart/system/library/db.php(45): DB\MySQLi->query('SET @@session.s...')
opencart_1        | #1 /opt/bitnami/opencart/install/cli_install.php(213): DB->query('SET @@session.s...')
opencart_1        | #2 /opt/bitnami/opencart/install/cli_install.php(133): setup_db(Array)
opencart_1        | #3 /opt/bitnami/opencart/install/cli_install.php(352): install(Array)
opencart_1        | #4 {main}
opencart_1        |   thrown in /opt/bitnami/opencart/system/library/db/mysqli.php on line 40

```

**Comment by juan131** [comment]
Hi @amuntasim 

This error suggests there could be some incompatibility issue with the database you're using:

> Fatal error: Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40' in /opt/bitnami/opencart/system/library/db/mysqli.php:40

What version of MySQL are you running in your Google Cloud SQL?

**Comment by amuntasim** [comment]
MySQL 8.0

**Comment by juan131** [comment]
Hi @amuntasim 

I also found issues using **MySQL 8.0** with the Docker Compose below:

```yaml
version: '2'
services:
  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_USER=bn_opencart
      - MYSQL_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/bitnami
  opencart:
    image: bitnami/opencart:3
    environment:
      - OPENCART_DATABASE_HOST=mysql
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - opencart_data:/bitnami
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local
```

While it seems it's working fine with 5.7, apply the changes:

```diff
...
  mysql:
-   image: bitnami/mysql:8.0
+   image: bitnami/mysql:5.7
    environment:
...
```

Could you please try with a MySQL 5.7 server?
