### ISSUE TITLE
I have modified "OPENCART_HOST" but it doesn't seem to work

### ISSUE THREAD

**Issue by bestpika** [bitnami/bitnami-docker-opencart#94]
**Description**

**Steps to reproduce the issue:**

1. create `docker-compose.yml`
1. modify `OPENCART_HOST`
1. execute `docker-compose up -d`
1. go to `http://192.168.1.2:9080` or `http://192.168.1.2:9443`

**Describe the results you received:**

The site does not display correctly.

![image](https://user-images.githubusercontent.com/5698157/106263651-a257a480-625f-11eb-876f-697978b3cea7.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

- `docker-compose.yml`

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '9080:8080'
      - '9443:8443'
    environment:
      - OPENCART_HOST=192.168.1.2
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
```

![image](https://user-images.githubusercontent.com/5698157/106263218-0cbc1500-625f-11eb-9085-11a7ea97a7f0.png)

**Comment by miguelaeh** [comment]
Hi @bestpika ,
I have been able to reproduce the issue. I will create an internal task to check why it is not properly set.
Thank you very much fore reporting it.

**Comment by alemorcuq** [comment]
Hi, @bestpika.

This `docker-compose.yml` works for me:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '9080:8080'
      - '9443:8443'
    environment:
      - OPENCART_HOST=192.168.1.35
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=9080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
```

There are two things to notice:

1. You need to set the `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` if you are using a custom port.
2. This is configured at initialization, so please make sure you don't have any persisted data from a previous deployment.


Regards,
Alejandro

**Comment by bestpika** [comment]
@alemorcuq For this container, I am not using a non-default port, so I don't think it should have anything to do with this issue.
If your settings work, then the problem should be that if I need to use `OPENCART_HOST` I should set `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` as well.

**Comment by bestpika** [comment]
@alemorcuq I tested your configuration and it did not work the way I wanted it to.
Is the IP address you set for `OPENCART_HOST` your localhost?

**Comment by alemorcuq** [comment]
> For this container, I am not using a non-default port, so I don't think it should have anything to do with this issue.

According to the `docker-compose.yml` file you shared, you are using ports `9080` and `9443` so you should set those ports.

>  Is the IP address you set for `OPENCART_HOST` your localhost?

Yes, it is.

> I tested your configuration and it did not work the way I wanted it to.

Can you describe that way?

**Comment by bestpika** [comment]
@alemorcuq My problem is that under my settings, his reference URLs are all "localhost".
So your modification does not solve my problem.

**Comment by alemorcuq** [comment]
As you can see in the attached picture, all the reference URLs include the IP and the port and not `localhost`:

![image](https://user-images.githubusercontent.com/47833905/110913414-68c19100-8315-11eb-9ecc-e8e5d0f88f6d.png)

As I said in my first comment, the Opencart host and external ports are only configured during the first initialization, since the configuration file is persisted. If you try to use the `OPENCART_HOST` or the `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` variables in an already existing installation, it's not going to have any effect on the configuration.

Can you try to do a new deployment, with no persisted data? That should work.

**Comment by huzaynbolt** [comment]
This might be related, If I set the `OPENCART_HOST ` to a domain name e.g _beta.alpha.com_. The client-facing part works fine. 
But an attempt to go to the admin page via _beta.alpha.com/admin_  will redirect the user to _beta.alpha.com:8080/admin_ which doesn't seem right.

**Comment by alemorcuq** [comment]
Are you setting the `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` variable as well, @huzaynbolt ?

**Comment by huzaynbolt** [comment]
@alemorcuq Yes I did but the redirection to admin still uses 8080. 
What I intend to achieve is a cleaner URL without the Port appearing. Just like the way it happens for the Client facing part.

Apparently, the same issue happens for the Prestashop implementation. I raised a similar issue [there](https://github.com/bitnami/bitnami-docker-prestashop/issues/111).

**Comment by alemorcuq** [comment]
I have reproduced the issue using port 80, @huzaynbolt. Strangely, it seems to be working for all ports except 80. We will be investigating this.

**Comment by alemorcuq** [comment]
By the way, @huzaynbolt, in the meantime you should be able to access the admin panel by going to `beta.alpha.com/admin/` instead of `beta.alpha.com/admin`. Don't forget the final slash.

**Comment by huzaynbolt** [comment]
Thanks that actually works.

**Comment by Eliah7** [comment]
I get a similar error but, when i ping the app over SSL then the javascript files load.
<img width="1043" alt="Screenshot 2021-07-08 at 10 52 29" src="https://user-images.githubusercontent.com/23521788/124884054-9a541b80-dfda-11eb-974d-dcd6a719bf9d.png">

But I then get javascript errors involving missing jQuery package.
<img width="1439" alt="Screenshot 2021-07-08 at 10 13 31" src="https://user-images.githubusercontent.com/23521788/124884139-af30af00-dfda-11eb-963d-84babaa834cf.png">
<img width="976" alt="Screenshot 2021-07-08 at 10 13 20" src="https://user-images.githubusercontent.com/23521788/124884146-b0fa7280-dfda-11eb-8116-ca7f16a4a6de.png">

What remains is when I navigate to the links in the page say desktop
<img width="226" alt="Screenshot 2021-07-08 at 10 54 25" src="https://user-images.githubusercontent.com/23521788/124884499-fe76df80-dfda-11eb-8b45-322c398e3c6e.png">
<img width="665" alt="Screenshot 2021-07-08 at 10 55 08" src="https://user-images.githubusercontent.com/23521788/124884508-0040a300-dfdb-11eb-968a-051be67d50b1.png">

**Comment by alemorcuq** [comment]
Can you share your `docker-compose.yml` file?

**Comment by mkile** [comment]
Same issue here:
`version: "3.7" # https://docs.docker.com/compose/compose-file/

services:
# Opencart
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - test_net
  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '9080:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=opencart
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=9080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - test_net
# Selenoid
  selenoid:
    networks:
      - test_net
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid_config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "test_net" ]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - test_net
    links:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  test_net:
    name: test_net
    driver: bridge

volumes:
  test_vol:
  opencart_data:
  opencart_storage_data:
  mariadb_data:`

**Comment by mkile** [comment]
I have simular issue, but I am running image on my PC. 
Opencart is not accessible from internal docker network at http://opencart. I can access it only at port 8080. 
But it still perfectly visible if I type http://localhost on my pc browser.
If I change external port to 8090 as suggested it stops loading correctly on pc too.

`version: "3.7" # https://docs.docker.com/compose/compose-file/

services:
# Opencart
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - test_net
  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=opencart
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - test_net
# Selenoid
  selenoid:
    networks:
      - test_net
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid_config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "test_net" ]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - test_net
    links:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  test_net:
    name: test_net
    driver: bridge

volumes:
  test_vol:
  opencart_data:
  opencart_storage_data:
  mariadb_data:`

![_______________________2021-07-15_180858](https://user-images.githubusercontent.com/13310837/125844515-84b804bd-7fea-4c1b-9c42-6c0efc3f15f8.png)
![_______________________2021-07-15_220222](https://user-images.githubusercontent.com/13310837/125844531-959a44e0-4b71-4118-b6ac-34a0aa7d6836.png)

**Comment by alemorcuq** [comment]
Well, if you want to access it by `http://opencart` you need to create an entry in your hosts file that points `opencart` to `127.0.0.1`. Otherwise your browser doesn't know what `opencart` is.

Regarding the port issue, can you share the docker-compose file you use to change the port? I don't see the `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` variable in the file you shared.

**Comment by alemorcuq** [comment]
I can't reproduce your issue. If I set `OPENCART_HOST` and `OPENCART_EXTERNAL_HTTP_NUMBER` URLs are properly generated:

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '8090:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=opencart.dev
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=8090
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
```

The result:

![image](https://user-images.githubusercontent.com/47833905/126745864-fe64ee91-8ce0-45a0-8a52-373e7b50d067.png)

But take into account that this is only setup during Opencart's first initialization. If you are restoring a persisted site, it won't be applied.

Regarding this:

> opencart is available in internal network only on internal port (8080) and not on set external port (except 8080).

I don't think this is a bug. The `OPENCART_EXTERNAL_HTTP_PORT_NUMBER` does not make Opencart listen on that port but generate URLs that include that port. For example, in the docker compose file I shared, the Apache server in the Opencart container is listening on port 8080, but I want to access the site through my host machine via port 8090 as I am mapping my port 8090 to the container's 8080. As such, I need to set `OPENCART_EXTERNAL_HTTP_PORT_NUMBER=8090`.
