### ISSUE TITLE
Restarting an OpenCart container results in the site being inoperable and 500 responses being returned

### ISSUE THREAD

**Issue by andykuszyk** [bitnami/bitnami-docker-opencart#95]
**Description**

Restarting an initialised OpenCart container--with a bind mount for the `/bitnami/opencart` directory--results in PHP errors and 500 responses.

**Steps to reproduce the issue:**

1. `mkdir -p ./volumes/opencart && mkdir -p ./volumes/mariadb/data`
1. `docker-compose up -d` using the `docker-compose.yml` file provided below.
2. Wait for the OpenCart container to be ready and visit http://localhost:80
3. OpenCart works as expected.
4. `docker-compose down && docker-compose up -d`
5. Wait for the container to be ready and re-visit http://localhost:80
6. The page fails to load and 500 is returned. The logs from the OpenCart container display a PHP error (details below).

**Describe the results you received:**
An error page in the browser with the following error:
```
Warning: fopen(/bitnami/opencart_storage/cache/cache.catalog.language.1613943696): failed to open stream: No such file or directory in /opt/bitnami/opencart/system/library/cache/file.php on line 49Warning: flock() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 51Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 53Warning: fflush() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 55Warning: flock() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 57Warning: fclose() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 59Warning: fopen(/bitnami/opencart_storage/cache/cache.currency.1613943696): failed to open stream: No such file or directory in /opt/bitnami/opencart/system/library/cache/file.php on line 49Warning: flock() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 51Warning: fwrite() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 53Warning: fflush() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 55Warning: flock() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 57Warning: fclose() expects parameter 1 to be resource, bool given in /opt/bitnami/opencart/system/library/cache/file.php on line 59Warning: fopen(/bitnami/opencart_storage/logs/error.log): failed to open stream: No such file or directory in /opt/bitnami/opencart/system/library/log.php on line 22
```

A PHP error in the container logs, as follows:
```
PHP Fatal error:  Uncaught Error: Class 'Twig\\Loader\\ArrayLoader' not found in /opt/bitnami/opencart/system/library/
template/twig.php:31\nStack trace:\n#0 /opt/bitnami/opencart/system/library/template.php(51): Template\\Twig->render('default/templat...', '{% if modules %...')\n#1 /opt/bitnami/opencart/system/engine/loa
der.php(125): Template->render('default/templat...', '')\n#2 /opt/bitnami/opencart/catalog/controller/common/column_left.php(72): Loader->view('common/column_l...', Array)\n#3 /opt/bitnami/opencart/system
/engine/action.php(79): ControllerCommonColumnLeft->index(Array)\n#4 /opt/bitnami/opencart/system/engine/loader.php(48): Action->execute(Object(Registry), Array)\n#5 /opt/bitnami/opencart/catalog/controll
er/common/home.php(12): Loader->controller('common/column_l...')\n#6 /opt/bitnami/opencart/system/engine/action.php(79): ControllerCommonHome->index()\n#7 /opt/bitnami/opencart/catalog/controller/startup/
router.php(25): Action->execute(Object(Registry))\n#8 /opt/bitnami/opencart/system/engine/action.php(79): ControllerStart in /opt/bitnami/opencart/system/library/template/twig.php on line 31
```

**Describe the results you expected:**
OpenCart to work normally following a container restart.

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker-compose.yml`:
```yml
version: "3"
services:
    opencart:
        image: bitnami/opencart:3.0.3-6-debian-10-r184
        user: root
        ports:
          - "80:8080"
          - "443:8443"
        environment:
          - OPENCART_HOST=localhost
          - OPENCART_USERNAME=test
          - OPENCART_PASSWORD=test
          - OPENCART_ENABLE_HTTPS=no
          - OPENCART_EMAIL=test@test.com
          - OPENCART_DATABASE_HOST=mariadb
          - OPENCART_DATABASE_PORT_NUMBER=3306
          - OPENCART_DATABASE_USER=opencart
          - OPENCART_DATABASE_PASSWORD=opencart
          - OPENCART_DATABASE_NAME=opencart
        volumes:
          - ./volumes/opencart:/bitnami/opencart
    mariadb:
      image: bitnami/mariadb:10.5.8
      user: root
      environment:
        - MARIADB_USER=opencart
        - MARIADB_PASSWORD=opencart
        - MARIADB_DATABASE=opencart
        - MARIADB_ROOT_PASSWORD=root
      volumes:
        - ./volumes/mariadb:/bitnami/mariadb
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 669
  Running: 2
  Paused: 0
  Stopped: 667
 Images: 512
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ojr7l9ppge6s6nkld09dkdbs0
  Is Manager: true
  ClusterID: dsbmvb9kgxxvvaqggf0ehnszg
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: YEZO:BAZJ:44DH:YH5Q:EHQZ:VDYP:XWFN:3FVF:3UNB:G2K5:77WH:2ELX
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 71
  Goroutines: 172
  System Time: 2021-02-21T20:49:38.6654994Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
- Running on MacOS Catalina, but also replicated on an Ubuntu server.
