### ISSUE TITLE
'/bitnami/opencart/config.php': No such file or directory

### ISSUE THREAD

**Issue by Olegt0rr** [bitnami/bitnami-docker-opencart#97]
**Description**

Can't launch existing opencart project via bitnami docker

**Steps to reproduce the issue:**

1. Prepare compose:
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_SKIP_BOOTSTRAP=yes
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./upload:/bitnami/opencart
      - ./storage:/bitnami/opencart_storage
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local

```
2. Run docker-compose up -d

**Describe the results you received:**

Bitnami tries to init new installation and then fails with weird exception `/bitnami/opencart/config.php': No such file or directory` (file exists - tree attached). Seems it can't overwrite the existing one

**Describe the results you expected:**

Bitnami just runs existing installation

**Additional information you deem important (e.g. issue happens only occasionally):**

```
opencart 10:52:06.26 Welcome to the Bitnami opencart container
opencart 10:52:06.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-opencart
opencart 10:52:06.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-opencart/issues
opencart 10:52:06.28 
opencart 10:52:06.29 INFO  ==> ** Starting OpenCart setup **
opencart 10:52:06.39 INFO  ==> Configuring PHP options
opencart 10:52:06.41 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
opencart 10:52:06.46 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
opencart 10:52:06.53 INFO  ==> Ensuring OpenCart directories exist
opencart 10:52:06.53 INFO  ==> Trying to connect to the database server
opencart 10:52:06.56 INFO  ==> An already initialized OpenCart database was provided, configuration will be skipped
opencart 10:52:06.57 INFO  ==> Generating configuration file
opencart 10:52:06.62 INFO  ==> Upgrading database schema
opencart 10:52:12.07 INFO  ==> Updating Opencart hostname
opencart 10:52:12.13 INFO  ==> Persisting OpenCart installation
cp: cannot create regular file '/bitnami/opencart/config.php': No such file or directory

```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 111
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: IHIP:Q5R5:3J6G:5DZP:TAKA:KGYT:XEHZ:PBRL:MQY7:GC2X:2AUQ:44WO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 57
  Goroutines: 62
  System Time: 2021-04-11T10:58:04.8088117Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**My local tree:**
```tree
.
├── docker-compose.yml
├── storage
│   ├── cache
│   ├── download
│   ├── logs
│   ├── modification
│   ├── session
│   ├── upload
│   └── vendor
└── upload
    ├── .htaccess
    ├── admin
    ├── catalog
    ├── config-dist.php
    ├── config.php
    ├── image
    ├── index.html
    ├── index.php
    ├── php.ini
    ├── robots.txt
    └── system

```

**Comment by Mauraza** [comment]
Hi @Olegt0rr,

Could you try to run the following command?
```
sudo chmod 775 storage/ upload/
```

**Comment by Olegt0rr** [comment]
@Mauraza, locally it doesn't help.
Seems I need to run it inside a container, but the container become closed immediately after the exception: `config.php: No such file or directory`.

Why bitnami ignores `OPENCART_SKIP_BOOTSTRAP=yes` and trying to install my app?

**Comment by Mauraza** [comment]
Hi @Olegt0rr,

I run the following docker-compose.yaml and it's working
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:3
    user: root
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_SKIP_BOOTSTRAP=yes
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './opencart_data:/bitnami/opencart'
      - './opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
```

> Why bitnami ignores OPENCART_SKIP_BOOTSTRAP=yes and trying to install my app?
https://github.com/bitnami/bitnami-docker-opencart/blob/9da16cbe21b8c39da9b36eace98375f16564a2dc/3/debian-10/rootfs/opt/bitnami/scripts/libopencart.sh#L122-L127 
if OPENCART_SKIP_BOOTSTRAP=no, then should appear in the logs "Running install script", does this message appear in your logs?
